FROM {{image}} as unsigned_image

COPY gsc-signer-key.pem /gsc-signer-key.pem

{% block path %} {% endblock %} \
    && gramine-sgx-sign \
         --key /gsc-signer-key.pem \
         --manifest /entrypoint.manifest \
         --output /entrypoint.manifest.sgx

# This trick removes all temporary files from the previous commands (including gsc-signer-key.pem)
FROM {{image}}

COPY --from=unsigned_image /*.sig /
COPY --from=unsigned_image /*.sgx /