{% extends "Dockerfile.common.sign.template" %}

{% block uninstall %}
RUN \
   pip3 uninstall -y click jinja2 \
      tomli tomli-w pyelftools voluptuous  \
   && zypper remove -y binutils \
      openssl \
      python3-cryptography \
      python3-protobuf \
   && zypper clean -a;

{% endblock %}

{% block path %} {{- python_path('/lib64') -}}{% endblock %}
