{% extends "Dockerfile.common.sign.template" %}

{% block uninstall %}
RUN \
   pip3 uninstall -y click jinja2 \
      tomli tomli-w pyelftools voluptuous  \
   && zypper remove -y binutils \
      openssl \
      python3-cryptography \
      python3-protobuf \
   && zypper clean -a;

{% endblock %}

{% block path %}export PYTHONPATH="${PYTHONPATH:+$PYTHONPATH:}$(find /gramine/meson_build_output/lib64 -type d -path '*/site-packages')" &&{% endblock %}
